version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5510:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
      #- ./postgres:/var/lib/postgresql/data

  
